var StockPrice = function () {
    this.priceMap = {};
    this.countMap = {};
    this.minQueue = new MinPriorityQueue();
    this.maxQueue = new MaxPriorityQueue();
    this.latestTimestamp = -Infinity;
    this.currentPrice;
};

/**
 * @param {number} timestamp
 * @param {number} price
 * @return {void}
 */
StockPrice.prototype.update = function (timestamp, price) {
    var oldPrice = this.priceMap[timestamp];

    if (oldPrice) {
        this.countMap[oldPrice]--;
    }

    this.priceMap[timestamp] = price;
    this.countMap[price] = (this.countMap[price] || 0) + 1;
    this.minQueue.enqueue(price);
    this.maxQueue.enqueue(price);

    if (timestamp >= this.latestTimestamp) {
        this.latestTimestamp = timestamp;
        this.currentPrice = price;
    }

    return null;
};

/**
 * @return {number}
 */
StockPrice.prototype.current = function () {
    return this.currentPrice;
};

/**
 * @return {number}
 */
StockPrice.prototype.maximum = function () {
    while (this.countMap[this.maxQueue.front()] === 0) {
        this.maxQueue.dequeue();
    }

    return this.maxQueue.front();
};

/**
 * @return {number}
 */
StockPrice.prototype.minimum = function () {
    while (this.countMap[this.minQueue.front()] === 0) {
        this.minQueue.dequeue();
    }

    return this.minQueue.front();
};

/**
 * Your StockPrice object will be instantiated and called as such:
 * var obj = new StockPrice()
 * obj.update(timestamp,price)
 * var param_2 = obj.current()
 * var param_3 = obj.maximum()
 * var param_4 = obj.minimum()
 */

const tests = [
    {
        input: {
            commands: [
                'StockPrice',
                'update',
                'update',
                'current',
                'maximum',
                'update',
                'maximum',
                'update',
                'minimum',
            ],
            values: [[], [1, 10], [2, 5], [], [], [1, 3], [], [4, 2], []],
        },
        output: [null, null, null, 5, 10, null, 5, null, 2],
    },
    {
        input: {
            commands: [
                'StockPrice',
                'update',
                'current',
                'current',
                'update',
                'update',
                'maximum',
                'minimum',
                'update',
                'current',
                'maximum',
                'update',
                'maximum',
                'maximum',
                'update',
                'maximum',
                'current',
                'minimum',
                'minimum',
                'update',
                'update',
                'maximum',
                'update',
                'maximum',
                'maximum',
                'update',
                'update',
                'maximum',
                'current',
                'minimum',
                'current',
                'maximum',
                'current',
                'maximum',
                'current',
                'update',
                'current',
                'current',
                'minimum',
                'update',
                'minimum',
                'update',
                'maximum',
                'update',
                'update',
                'update',
                'update',
                'minimum',
                'maximum',
                'minimum',
                'update',
                'current',
                'update',
                'update',
                'update',
                'maximum',
                'current',
                'maximum',
                'current',
                'update',
                'current',
                'maximum',
                'maximum',
                'update',
                'maximum',
                'current',
                'maximum',
                'update',
                'current',
                'update',
                'maximum',
                'maximum',
                'maximum',
                'current',
                'minimum',
                'maximum',
                'current',
                'current',
                'current',
                'minimum',
                'minimum',
                'current',
                'maximum',
                'minimum',
                'minimum',
                'update',
                'minimum',
                'update',
                'minimum',
                'current',
                'minimum',
                'current',
                'maximum',
                'minimum',
                'minimum',
                'maximum',
                'minimum',
                'current',
                'minimum',
                'current',
                'minimum',
                'minimum',
                'current',
                'minimum',
                'minimum',
                'maximum',
                'maximum',
                'current',
                'maximum',
                'current',
                'maximum',
                'update',
                'current',
                'current',
                'current',
                'minimum',
                'current',
                'minimum',
                'maximum',
                'update',
                'current',
                'maximum',
                'update',
                'minimum',
                'current',
                'minimum',
                'current',
                'update',
                'minimum',
                'update',
                'maximum',
                'update',
                'update',
                'minimum',
                'current',
                'update',
                'update',
                'maximum',
                'update',
                'maximum',
                'current',
                'update',
                'current',
                'maximum',
                'minimum',
                'maximum',
                'minimum',
                'current',
                'minimum',
                'update',
                'minimum',
                'current',
            ],
            values: [
                [],
                [765, 3848],
                [],
                [],
                [765, 8511],
                [853, 6124],
                [],
                [],
                [765, 5733],
                [],
                [],
                [832, 5725],
                [],
                [],
                [799, 1311],
                [],
                [],
                [],
                [],
                [793, 4708],
                [849, 9940],
                [],
                [757, 3154],
                [],
                [],
                [847, 9940],
                [834, 6830],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [820, 2754],
                [],
                [],
                [],
                [826, 3783],
                [],
                [794, 7551],
                [],
                [837, 3666],
                [834, 7067],
                [779, 2754],
                [832, 7551],
                [],
                [],
                [],
                [839, 982],
                [],
                [839, 1283],
                [836, 3960],
                [846, 7223],
                [],
                [],
                [],
                [],
                [776, 4337],
                [],
                [],
                [],
                [827, 6830],
                [],
                [],
                [],
                [820, 7223],
                [],
                [765, 9265],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [826, 1987],
                [],
                [771, 2494],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [811, 3154],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [848, 7223],
                [],
                [],
                [794, 839],
                [],
                [],
                [],
                [],
                [758, 1283],
                [],
                [794, 2206],
                [],
                [758, 1204],
                [820, 3259],
                [],
                [],
                [854, 1379],
                [842, 3848],
                [],
                [803, 1461],
                [],
                [],
                [846, 1310],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [779, 1556],
                [],
                [],
            ],
        },
        output: [
            null,
            null,
            3848,
            3848,
            null,
            null,
            8511,
            6124,
            null,
            6124,
            6124,
            null,
            6124,
            6124,
            null,
            6124,
            6124,
            1311,
            1311,
            null,
            null,
            9940,
            null,
            9940,
            9940,
            null,
            null,
            9940,
            6124,
            1311,
            6124,
            9940,
            6124,
            9940,
            6124,
            null,
            6124,
            6124,
            1311,
            null,
            1311,
            null,
            9940,
            null,
            null,
            null,
            null,
            1311,
            9940,
            1311,
            null,
            6124,
            null,
            null,
            null,
            9940,
            6124,
            9940,
            6124,
            null,
            6124,
            9940,
            9940,
            null,
            9940,
            6124,
            9940,
            null,
            6124,
            null,
            9940,
            9940,
            9940,
            6124,
            1283,
            9940,
            6124,
            6124,
            6124,
            1283,
            1283,
            6124,
            9940,
            1283,
            1283,
            null,
            1283,
            null,
            1283,
            6124,
            1283,
            6124,
            9940,
            1283,
            1283,
            9940,
            1283,
            6124,
            1283,
            6124,
            1283,
            1283,
            6124,
            1283,
            1283,
            9940,
            9940,
            6124,
            9940,
            6124,
            9940,
            null,
            6124,
            6124,
            6124,
            1283,
            6124,
            1283,
            9940,
            null,
            6124,
            9940,
            null,
            839,
            6124,
            839,
            6124,
            null,
            839,
            null,
            9940,
            null,
            null,
            1204,
            6124,
            null,
            null,
            9940,
            null,
            9940,
            1379,
            null,
            1379,
            9940,
            1204,
            9940,
            1204,
            1379,
            1204,
            null,
            1204,
            1379,
        ],
    },
    {
        input: {
            commands: [
                'StockPrice',
                'update',
                'maximum',
                'current',
                'minimum',
                'maximum',
                'maximum',
                'maximum',
                'minimum',
                'minimum',
                'maximum',
                'update',
                'maximum',
                'minimum',
                'update',
                'maximum',
                'minimum',
                'current',
                'maximum',
                'update',
                'minimum',
                'maximum',
                'update',
                'maximum',
                'maximum',
                'current',
                'update',
                'current',
                'minimum',
                'update',
                'update',
                'minimum',
                'minimum',
                'update',
                'current',
                'update',
                'maximum',
                'update',
                'minimum',
            ],
            values: [
                [],
                [38, 2308],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [],
                [47, 7876],
                [],
                [],
                [58, 1866],
                [],
                [],
                [],
                [],
                [43, 121],
                [],
                [],
                [40, 5339],
                [],
                [],
                [],
                [32, 5339],
                [],
                [],
                [43, 6414],
                [49, 9369],
                [],
                [],
                [36, 3192],
                [],
                [48, 1006],
                [],
                [53, 8013],
                [],
            ],
        },
        output: [
            null,
            null,
            2308,
            2308,
            2308,
            2308,
            2308,
            2308,
            2308,
            2308,
            2308,
            null,
            7876,
            2308,
            null,
            7876,
            1866,
            1866,
            7876,
            null,
            121,
            7876,
            null,
            7876,
            7876,
            1866,
            null,
            1866,
            121,
            null,
            null,
            1866,
            1866,
            null,
            1866,
            null,
            9369,
            null,
            1006,
        ],
    },
    {
        input: {
            commands: [
                'StockPrice',
                'update',
                'minimum',
                'update',
                'update',
                'minimum',
                'minimum',
                'update',
                'maximum',
                'update',
                'minimum',
                'current',
                'minimum',
                'update',
                'current',
                'minimum',
                'current',
                'current',
                'update',
                'maximum',
                'maximum',
                'update',
                'minimum',
                'minimum',
                'maximum',
                'maximum',
                'update',
                'maximum',
                'current',
                'maximum',
                'minimum',
                'minimum',
                'update',
                'current',
            ],
            values: [
                [],
                [45, 9233],
                [],
                [55, 9651],
                [37, 3902],
                [],
                [],
                [25, 4833],
                [],
                [53, 4521],
                [],
                [],
                [],
                [22, 1161],
                [],
                [],
                [],
                [],
                [55, 6897],
                [],
                [],
                [20, 5354],
                [],
                [],
                [],
                [],
                [30, 5623],
                [],
                [],
                [],
                [],
                [],
                [25, 2725],
                [],
            ],
        },
        output: [
            null,
            null,
            9233,
            null,
            null,
            3902,
            3902,
            null,
            9651,
            null,
            3902,
            9651,
            3902,
            null,
            9651,
            1161,
            9651,
            9651,
            null,
            9233,
            9233,
            null,
            1161,
            1161,
            9233,
            9233,
            null,
            9233,
            6897,
            9233,
            1161,
            1161,
            null,
            6897,
        ],
    },
];

import deepEqual from 'deep-eql';
import {
    MinPriorityQueue,
    MaxPriorityQueue,
} from '@datastructures-js/priority-queue';

for (const test of tests) {
    const result = [];
    var obj;

    for (let i = 0; i < test.input.commands.length; i++) {
        const command = test.input.commands[i];
        const values = test.input.values[i];

        if (command === 'StockPrice') {
            obj = new StockPrice(...values);
            result.push(null);
            continue;
        }

        result.push(obj[command](...values));
        if (result[i] !== test.output[i]) {
            console.dir(
                {
                    i,
                    command,
                    values,
                    result: result[i],
                    expected: test.output[i],
                    obj,
                },
                { depth: 4 }
            );
            break;
        }
    }

    if (!deepEqual(result, test.output)) {
        console.log('❌ fail:');
        console.dir(
            { ...test.input, result, expected: test.output },
            { depth: null }
        );
    } else {
        console.log('✅ pass');
    }
}
